/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dxtest_simpleastffmpeg_JniFFmpeg03DecoderTest */

#ifndef _Included_com_dxtest_simpleastffmpeg_JniFFmpeg03DecoderTest
#define _Included_com_dxtest_simpleastffmpeg_JniFFmpeg03DecoderTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dxtest_simpleastffmpeg_JniFFmpeg03DecoderTest
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dxtest_simpleastffmpeg_JniFFmpeg03DecoderTest_decode
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_dxtest_simpleastffmpeg_JniFFmpeg03DecoderTest
 * Method:    deCodeVideo
 * Signature: (Ljava/lang/String;Landroid/view/Surface;)I
 */
JNIEXPORT jint JNICALL Java_com_dxtest_simpleastffmpeg_JniFFmpeg03DecoderTest_deCodeVideo
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
