/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dxtest_simpleastffmpeg_JniFFmpeg02Decoder */

#ifndef _Included_com_dxtest_simpleastffmpeg_JniFFmpeg02Decoder
#define _Included_com_dxtest_simpleastffmpeg_JniFFmpeg02Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dxtest_simpleastffmpeg_JniFFmpeg02Decoder
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dxtest_simpleastffmpeg_JniFFmpeg02Decoder_decode
  (JNIEnv *, jobject, jstring, jstring);

JNIEXPORT jint JNICALL Java_com_dxtest_simpleastffmpeg_JniFFmpeg02Decoder_deCodeVideo
(JNIEnv *env, jobject instance, jstring input_, jobject surface);

#ifdef __cplusplus
}
#endif
#endif
