/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

//实现pthread 需要包括的接口
#include <unistd.h>
#include <pthread.h>
/* Header for class com_dxtest_simpleastffmpeg_threadpool_ThreadPool */

#ifndef _Included_com_dxtest_simpleastffmpeg_threadpool_ThreadPool
#define _Included_com_dxtest_simpleastffmpeg_threadpool_ThreadPool
#ifdef __cplusplus
#endif
/*
 * Class:     com_dxtest_simpleastffmpeg_threadpool_ThreadPool
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dxtest_simpleastffmpeg_threadpool_ThreadPool_init
  (JNIEnv *, jobject);

/*
 * Class:     com_dxtest_simpleastffmpeg_threadpool_ThreadPool
 * Method:    run
 * Signature: (Lcom/dxtest/simpleastffmpeg/threadpool/LocalRunnable;)I
 */
JNIEXPORT jint JNICALL Java_com_dxtest_simpleastffmpeg_threadpool_ThreadPool_run
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_dxtest_simpleastffmpeg_threadpool_ThreadPool
 * Method:    recycle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dxtest_simpleastffmpeg_threadpool_ThreadPool_recycle
  (JNIEnv *, jobject);

#ifdef __cplusplus
#endif
#endif
